name: API Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Start API in background
        run: |
          npm run compile
          npm start &
          sleep 5 # wait for the server to start

      - name: Run Playwright tests
        uses: actions/checkout@v3
        with:
          repository: yarikpavlin/suber-tests
          path: ./tests

      - name: Install Playwright
        run: |
          cd tests
          npm ci

      - name: Run API tests
        run: |
          cd tests
          npx playwright test -g @api